export enum SAGA_TYPES {
  INVOICE_SEND = 'INVOICE_SEND',
}

export enum INVOICE_SEND_SAGA_STEP {
  GENERATE_PDF = 'GENERATE_PDF',
  UPLOAD_FILE = 'UPLOAD_FILE',
  CREATE_PAYMENT_LINK = 'CREATE_PAYMENT_LINK',
  FINALIZE_SEND = 'FINALIZE_SEND',
}

export enum SAGA_STATUS {
  PENDING = 'PENDING',
  RUNNING = 'RUNNING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  COMPENSATING = 'COMPENSATING',
  COMPENSATED = 'COMPENSATED',
  COMPENSATE_FAILED = 'COMPENSATE_FAILED',
}

export enum SAGA_STEP_STATUS {
  PENDING = 'PENDING',
  RUNNING = 'RUNNING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  SKIPPED = 'SKIPPED',
  COMPENSATING = 'COMPENSATING',
  COMPENSATED = 'COMPENSATED',
  COMPENSATE_FAILED = 'COMPENSATE_FAILED',
}
